-- Run once as ACCOUNTADMIN to provision pipeline infrastructure

-- Warehouse: auto-suspends after 60s to preserve trial credits
CREATE WAREHOUSE IF NOT EXISTS PIPELINE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Database and schemas
CREATE DATABASE IF NOT EXISTS WEATHER_DB;

CREATE SCHEMA IF NOT EXISTS WEATHER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.MARTS;

-- Dedicated role for the pipeline
CREATE ROLE IF NOT EXISTS PIPELINE_ROLE;

GRANT USAGE ON WAREHOUSE PIPELINE_WH TO ROLE PIPELINE_ROLE;
GRANT USAGE ON DATABASE WEATHER_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE WEATHER_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE WEATHER_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE WEATHER_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE WEATHER_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE WEATHER_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE WEATHER_DB TO ROLE PIPELINE_ROLE;

-- Grant pipeline role to ACCOUNTADMIN for this portfolio setup
GRANT ROLE PIPELINE_ROLE TO ROLE ACCOUNTADMIN;

-- Raw ingestion table (append-only, all strings — dbt handles casting)
CREATE TABLE IF NOT EXISTS WEATHER_DB.RAW.RAW_WEATHER_DAILY (
    city            VARCHAR,
    latitude        VARCHAR,
    longitude       VARCHAR,
    date            VARCHAR,
    temp_max_c      VARCHAR,
    temp_min_c      VARCHAR,
    precipitation_mm VARCHAR,
    windspeed_max_kmh VARCHAR,
    loaded_at       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
